alter table STATISTICSPROJECTRC_ORDERS
    add constraint FK_STATISTICSPROJECTRC_ORDERS_ON_PRODUCT foreign key (PRODUCT_ID) references STATISTICSPROJECTRC_FORM_DURATION_COST (ID);
create index IDX_STATISTICSPROJECTRC_ORDERS_ON_PRODUCT on STATISTICSPROJECTRC_ORDERS (PRODUCT_ID);
