alter table STATISTICSPROJECTRC_FORMSERVICE add column DATE_START_SERVICE date ^
update STATISTICSPROJECTRC_FORMSERVICE set DATE_START_SERVICE = current_date where DATE_START_SERVICE is null ;
alter table STATISTICSPROJECTRC_FORMSERVICE alter column DATE_START_SERVICE set not null ;
