create unique index IDX_STATISTICSPROJECTRC_WSITE_UNIQ_SITE_NAME on STATISTICSPROJECTRC_WSITE (SITE_NAME) ;
create unique index IDX_STATISTICSPROJECTRC_WSITE_UNIQ_SITE_REGION on STATISTICSPROJECTRC_WSITE (SITE_REGION) ;
create unique index IDX_STATISTICSPROJECTRC_WSITE_UNIQ_URL_SITE on STATISTICSPROJECTRC_WSITE (URL_SITE) ;
