alter table STATISTICSPROJECTRC_PROJECT_CONSULTANT
    alter column CONSULTANT_ID rename to CONSULTANT_ID__U56785 ^
alter table STATISTICSPROJECTRC_PROJECT_CONSULTANT
    alter column CONSULTANT_ID__U56785 set null;
alter table STATISTICSPROJECTRC_PROJECT_CONSULTANT
    drop constraint FK_STATISTICSPROJECTRC_PROJECT_CONSULTANT_ON_CONSULTANT;
drop index IDX_STATISTICSPROJECTRC_PROJECT_CONSULTANT_ON_CONSULTANT;
