alter table STATISTICSPROJECTRC_ORDERS
    add constraint FK_STATISTICSPROJECTRC_ORDERS_ON_CONSULTANT foreign key (CONSULTANT_ID) references STATISTICSPROJECTRC_CONSULTANTS (ID);
create index IDX_STATISTICSPROJECTRC_ORDERS_ON_CONSULTANT on STATISTICSPROJECTRC_ORDERS (CONSULTANT_ID);
