alter table STATISTICSPROJECTRC_SECTION_CONSULTANT alter column SECTION_ID rename to SECTION_ID__U11769 ^
alter table STATISTICSPROJECTRC_SECTION_CONSULTANT alter column SECTION_ID__U11769 set null ;
drop index IDX_STATISTICSPROJECTRC_SECTION_CONSULTANT_ON_SECTION ;
-- alter table STATISTICSPROJECTRC_SECTION_CONSULTANT add column SECTION_ID varchar(36) ^
-- update STATISTICSPROJECTRC_SECTION_CONSULTANT set SECTION_ID = <default_value> ;
-- alter table STATISTICSPROJECTRC_SECTION_CONSULTANT alter column SECTION_ID set not null ;
alter table STATISTICSPROJECTRC_SECTION_CONSULTANT add column SECTION_ID varchar(36) not null ;
